version: "3.1"

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./docker/pg:/var/lib/postgresql
    ports:
      - 5433:5432
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  backend:
    container_name: backend
    build: ./backend/
    image: backend
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app:cached
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - 5001:3000 # ポートフォワード
    networks:
      app_net:
        ipv4_address: '172.20.0.3'

  frontend:
    container_name: front
    build: ./frontend/
    image: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: "npm run dev"
    networks:
      app_net:
        ipv4_address: '172.20.0.4'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data:
  bundle_data:
